#!/bin/bash

MINISH=minishell;
SLEEPFOR=2;

# while pgrep minishell
while true
do
	tput clear
	leaks ${MINISH} | grep -A15 "for" | grep --color -E '^.*'
	sleep ${SLEEPFOR}
done
echo "${MINISH} has stopped."
